name: CI/CD PIPELINE

on:
  push:
    branches: ["deploy-sankar-satyam"]
  pull_request:
    branches: ["deploy-sankar-satyam"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: test for echo script
      run : echo "Hello World"
      
