name: CI/CD PIPELINE

on:
  push:
    branches: ["deploy-sankar-satyam"]
  pull_request:
    branches: ["deploy-sankar-satyam"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        java-version: '17'
    - name: Run test
      run:  |
        ./gradlew test
        
  build-gradle-project:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Create the shadowJar
      run: ./gradlew shadowJar
    - name: Upload shadowJar
      uses: actions/upload-artifact@v3
      with:
        name: shadowJar.jar
        path: build/libs/
  
  deploy-to-ec2:
    needs: build-gradle-project
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the files
      uses: actions/checkout@v2
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: shadowJar.jar
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        key: ${{ secrets.EC2_SSH_KEY }}
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        script: |
          scp -i sahdowJar.jar ec2user@ec2-3-109-62-206.ap-south-1.compute.amazonaws.com:~
