on:
  push:
    branches:
      - infra-main

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform init
        run : terraform -chdir=infrastructure init -backend-config="access_key=${{ secrets.ACCESS_KEY }}" -backend-config="secret_key=${{ secrets.ACCESS_VALUE}}" -backend-config="region=ap-south-1"

      - name: Terraform plan
        run: terraform -chdir=infrastructure plan -out=tfplan

      - name: Terraform init
        run: terraform -chdir=infrastructure apply "tfplan"




